Repository prgrms-web-devcourse-final-project/WEB1_1_Urdego_FE, pull requests merged in 2024-11, with the labels that each got.

#11 Feature/#9: prettier 적용
  .prettierignore
  .prettierrc
  package-lock.json
  package.json
Labels: ✨ feature

#10 Feature/#2: Common Button 컴포넌트 제작 및 하단 NavBar 컴포넌트 제작
  app/(nav)/home/page.tsx
  app/(nav)/layout.tsx
  app/(nav)/myPage/page.tsx
  app/(nav)/placeRegister/page.tsx
  app/(nav)/rank/page.tsx
  app/layout.tsx
  app/metadata.ts
  app/page.tsx
  components/common/Button/Button.styles.ts
  components/common/Button/Button.tsx
  components/common/NavBar/NavBar.styles.ts
  components/common/NavBar/NavBar.tsx
  components/common/NavBar/NavIcon.tsx
  lib/registry.tsx
  next.config.mjs
  stories/Common/CommonButton.stories.tsx
  stories/Common/NavBar.stories.tsx
  styles/Container.ts
  styles/GlobalStyle.ts
  styles/Icon/Home.svg
  styles/Icon/HomeColor.svg
  styles/Icon/Map.svg
  styles/Icon/MapColor.svg
  styles/Icon/Mypage.svg
  styles/Icon/MypageColor.svg
  styles/Icon/Plus.svg
  styles/Icon/PlusIcon.png
  styles/Icon/Star.svg
  styles/Icon/StarColor.svg
Labels: ✨ feature, 🎨 design

#17 Feature/#12: 메인 화면 채널 및 장소 라벨 컴포넌트 및 스토리북 구현
  app/(nav)/home/page.tsx
  components/Common/RoomButton/RoomButton.styles.ts
  components/Common/RoomButton/RoomButton.tsx
  components/Common/RoomButton/RoomButtonIcon.tsx
  components/Layout/Home/ChannelButton/ChannelButton.styles.ts
  components/Layout/Home/ChannelButton/ChannelButton.tsx
  components/Layout/Home/ChannelButton/ChannelButtonIcon.tsx
  components/Layout/Home/LocationButton/LocationButton.styles.ts
  components/Layout/Home/LocationButton/LocationButton.tsx
  components/Layout/Home/LocationButton/LocationButtonIcon.tsx
  stories/Common/RoomButton.stories.tsx
  stories/Layout/Home/ChannelButton.stories.ts
  stories/Layout/Home/LocationButton.stories.ts
  stories/Layout/Signup/NickNameInput.stories.ts
  styles/GlobalStyle.ts
  styles/Icon/ArrowRightSmall.svg
  styles/Icon/Entrance.svg
  styles/Icon/EyeClose.svg
  styles/Icon/EyeOpen.svg
  styles/Icon/Lock.svg
  styles/Icon/Person.svg
  styles/Icon/Refresh.svg
Labels: ✨ feature, 🎨 design

#21 Feature/#19 login UI 컴포넌트 구현
  components/Common/ValidationMessage/validationMessage.styles.ts
  components/Common/ValidationMessage/validationMessage.tsx
  components/Layout/Login/AutoLogin.styles.ts
  components/Layout/Login/AutoLogin.tsx
  components/Layout/Login/SNSLogos.styles.ts
  components/Layout/Login/SNSLogos.tsx
  components/Layout/Login/SignUpTabs.styles.ts
  components/Layout/Login/SignUpTabs.tsx
  stories/Common/ValidationMessage.stories.tsx
  stories/Layout/Login/SNSLogos.stories.ts
  stories/Layout/Login/SignUpTabs.stories.tsx
  styles/Icon/sns-google-login.svg
  styles/Icon/sns-kakao-login.svg
  styles/Icon/sns-naver-login.svg
Labels: ✨ feature, 🎨 design

#20 Feature/#15 상단 네비바 + 상단 배너 제작
  app/(nav)/home/page.tsx
  app/(nav)/layout.tsx
  app/(nav)/myPage/page.tsx
  app/(nav)/placeRegister/page.tsx
  app/(nav)/rank/page.tsx
  components/Common/Button/Button.tsx
  components/Common/Input/Input.tsx
  components/Common/NavBar/NavBar.tsx
  components/Common/TopBar/TopBar.styles.ts
  components/Common/TopBar/TopBar.tsx
  components/Common/TopBar/TopBarIcon.tsx
  components/Layout/MainBanner/Level.styles.ts
  components/Layout/MainBanner/Level.tsx
  components/Layout/MainBanner/MainBanner.styles.ts
  components/Layout/MainBanner/MainBanner.tsx
  components/Layout/MainBanner/UserCharacter.styles.ts
  components/Layout/MainBanner/UserCharacter.tsx
  stories/Common/TopBar.stories.tsx
  styles/Icon/Alarm.svg
  styles/Icon/Back.svg
  styles/Icon/Friends.svg
  styles/Icon/PlusIcon.png
  styles/Icon/UserCharacter.svg
  tsconfig.json
Labels: ✨ feature, 🎨 design

#25 Feat: 전체 import 경로 수정 및 css box-sizing 적용
  app/(nav)/home/Home.styles.ts
  app/(nav)/home/page.tsx
  app/signup/page.tsx
  components/Layout/Home/MainBanner/Level.styles.ts
  components/Layout/Home/MainBanner/Level.tsx
  components/Layout/Home/MainBanner/MainBanner.styles.ts
  components/Layout/Home/MainBanner/MainBanner.tsx
  components/Layout/Home/MainBanner/UserCharacter.styles.ts
  components/Layout/Home/MainBanner/UserCharacter.tsx
  tsconfig.json
Labels: 🐛 bug

#28 Featur/#22 login UI implementation
  app/(auth)/layout.styles.ts
  app/(auth)/layout.tsx
  app/(auth)/login/Login.styles.ts
  app/(auth)/login/page.tsx
  app/(auth)/signup/Signup.styles.ts
  app/(auth)/signup/page.tsx
  components/Common/Button/Button.styles.ts
  components/Common/Button/Button.tsx
  components/Layout/Login/SNSLogos.styles.ts
Labels: ✨ feature, 🎨 design, 📝 docs

#29 Feature/#24: 장소 등록 컴포넌트 구현
  app/(nav)/placeRegister/PlaceRegister.styles.ts
  app/(nav)/placeRegister/page.tsx
  components/Layout/PlaceRegister/ImageUpload.styles.ts
  components/Layout/PlaceRegister/ImageUpload.tsx
  components/Layout/PlaceRegister/ImageUploadIcon.tsx
  components/Layout/PlaceRegister/PlaceInput.styles.ts
  components/Layout/PlaceRegister/PlaceInput.tsx
  components/Layout/PlaceRegister/PlaceInputIcon.tsx
  components/Layout/PlaceRegister/PlaceRegister.styles.ts
  components/Layout/PlaceRegister/PlaceRegister.tsx
  components/Layout/PlaceRegister/PlaceRegisterIcon.tsx
  components/Layout/PlaceRegister/PlaceSearchButton.styles.ts
  components/Layout/PlaceRegister/PlaceSearchButton.tsx
  components/Layout/PlaceRegister/PlaceSearchButtonIcon.tsx
  styles/Container.ts
  styles/Icon/Clear.svg
  styles/Icon/Gallery.svg
  styles/Icon/Search.svg
  styles/Icon/Trash.svg
Labels: ✨ feature, 🎨 design

#33 Fix: Global CSS 수정
  app/(auth)/layout.styles.ts
  app/(auth)/login/page.tsx
  app/(auth)/signup/Signup.styles.ts
  app/(auth)/signup/page.tsx
  app/(nav)/groupList/page.tsx
  app/(nav)/home/Home.styles.ts
  app/(nav)/home/page.tsx
  app/(nav)/placeRegister/page.tsx
  app/(nav)/rank/page.tsx
  app/commonPage.styles.ts
  app/makeRoom/page.tsx
  components/Common/TopBar/TopBar.styles.ts
  components/Layout/Home/MainBanner/MainBanner.styles.ts
  styles/Container.ts
Labels: 🐛 bug, 🎨 design

#36 Feature/#31 in game UI 및 기능 구현
  .gitignore
  app/(auth)/signup/Signup.styles.ts
  app/(auth)/signup/page.tsx
  app/game/[round]/game.styles.ts
  app/game/[round]/page.tsx
  app/game/[round]/roundRank/page.tsx
  app/game/layout.tsx
  components/Common/TopBar/TopBar.styles.ts
  components/Common/TopBar/TopBar.tsx
  components/Layout/Game/GoogleMap.tsx
  components/Layout/Game/ProgressBar.styles.ts
  components/Layout/Game/ProgressBar.tsx
  components/Layout/Game/RankList.styles.ts
  components/Layout/Game/RankList.tsx
  components/Layout/Game/Swiper.styles.ts
  components/Layout/Game/Swiper.tsx
  package-lock.json
  package.json
  styles/Container.ts
  styles/Icon/UserProfile.svg
Labels: ✨ feature, 🎨 design

#38 Feature/#34: 장소 등록 다중 이미지 저장 기능 구현
  app/(nav)/placeRegister/PlaceRegister.styles.ts
  app/(nav)/placeRegister/page.tsx
  components/Common/Button/Button.styles.ts
  components/Layout/PlaceRegister/ImageUpload.styles.ts
  components/Layout/PlaceRegister/ImageUpload.tsx
  components/Layout/PlaceRegister/PlaceInput.styles.ts
  components/Layout/PlaceRegister/PlaceInput.tsx
  components/Layout/PlaceRegister/PlaceRegister.styles.ts
  components/Layout/PlaceRegister/PlaceRegister.tsx
  hooks/placeRegister/useRegisterFiles.ts
  hooks/placeRegister/useUploadFiles.ts
  hooks/placeRegister/useWatchInputComplete.ts
  stores/placeRegisterModeStore.ts
  styles/Icon/Plus.svg
Labels: ✨ feature

#40 Feature/#32: 로그인 회원가입 기능 구현 완료
  .gitignore
  app/(auth)/layout.styles.ts
  app/(auth)/layout.tsx
  app/(auth)/login/Login.styles.ts
  app/(auth)/login/page.tsx
  app/(auth)/signup/Signup.styles.ts
  app/(auth)/signup/page.tsx
  app/commonPage.styles.ts
  components/Common/Button/Button.tsx
  components/Common/Input/Input.styles.ts
  components/Common/Input/Input.tsx
  components/Common/ValidationMessage/validationMessage.styles.ts
  components/Layout/Signup/NickNameInput.styles.ts
  components/Layout/Signup/NickNameInput.tsx
  stores/useUserStore.ts
Labels: ✨ feature, 🎨 design

#45 Feature/#39: 장소 등록 화면에서 단일 장소 정보 전송 및 버튼 제어 구현
  app/(nav)/placeRegister/PlaceRegister.styles.ts
  app/(nav)/placeRegister/page.tsx
  components/Common/Button/Button.styles.ts
  components/Common/Button/Button.tsx
  components/Layout/PlaceRegister/ImageUpload.tsx
  components/Layout/PlaceRegister/PlaceInput.tsx
  components/Layout/PlaceRegister/PlaceRegister.styles.ts
  components/Layout/PlaceRegister/PlaceRegister.tsx
  components/Layout/PlaceRegister/PlaceRegisterIcon.tsx
  hooks/placeRegister/useContorlButtons.ts
  hooks/placeRegister/useRegisterFiles.ts
  hooks/placeRegister/useUploadFiles.ts
  hooks/placeRegister/useWatchInputComplete.ts
  package-lock.json
  package.json
  stores/placeRegisterModeStore.ts
  stores/placeRegisterStore.ts
  styles/Container.ts
Labels: ✨ feature

#44 Feature/#43 : 게임 대기방 준비 상태 관리 추가
  app/game/[roomId]/[round]/roundRank/page.tsx
  app/game/[roomId]/waitingRoom/page.tsx
  components/Layout/Game/Character.styles.ts
  components/Layout/Game/Character.tsx
  components/Layout/Game/GoogleMap.tsx
Labels: ✨ feature

#49 Feat/#47: API 엔드 포인트 구현 및 서버 통신 구현
  app/api/content/route.ts
  hooks/placeRegister/useUploadFiles.ts
Labels: ✨ feature

#50 Feature/#35 방만들기 UI, 기능 구현
  app/layout.tsx
  app/makeRoom/makeRoom.styles.ts
  app/makeRoom/page.tsx
  components/Common/TopBar/TopBar.tsx
  components/Layout/MakeRoom/FriendsInviteForm.styles.ts
  components/Layout/MakeRoom/FriendsInviteForm.tsx
  components/Layout/MakeRoom/InviteButton.styles.ts
  components/Layout/MakeRoom/InviteButton.tsx
  components/Layout/MakeRoom/NumSelectForm.styles.ts
  components/Layout/MakeRoom/NumSelectForm.tsx
  components/Layout/MakeRoom/RoomTitleInput.styles.ts
  components/Layout/MakeRoom/RoomTitleInput.tsx
  package-lock.json
  package.json
  styles/Icon/minusIcon.svg
  styles/Icon/plusIcon.svg
  tsconfig.json
Labels: ✨ feature, 🎨 design

#52 Fix/#51 방만들기 버그 고쳤습니다.
  app/makeRoom/page.tsx
  components/Common/Button/Button.tsx
  components/Layout/MakeRoom/FriendsInviteForm.tsx
Labels: ✨ feature

#53 Feature/#42: 장소 등록에서 미리보기-장소 삭제 구현
  app/(nav)/placeRegister/page.tsx
  components/Layout/PlaceRegister/ImageUpload.tsx
  components/Layout/PlaceRegister/ImageUploadIcon.tsx
  components/Layout/PlaceRegister/PlaceInputIcon.tsx
  components/Layout/PlaceRegister/PlaceRegister.styles.ts
  components/Layout/PlaceRegister/PlaceRegister.tsx
  components/Layout/PlaceRegister/PlaceRegisterIcon.tsx
  hooks/placeRegister/useContorlButtons.ts
  hooks/placeRegister/useRegisterFiles.ts
  hooks/placeRegister/useUploadFiles.ts
  stores/placeRegisterStore.ts
  styles/Icon/BlackClear.svg
Labels: ✨ feature, 🎨 design

#57 deploy : 배포 에러 해결(1)
  app/(auth)/login/page.tsx
  app/game/[roomId]/[round]/game.styles.ts
  app/game/[roomId]/[round]/page.tsx
  app/game/[roomId]/[round]/roundRank/page.tsx
  components/Common/Button/Button.styles.ts
  components/Common/Button/Button.tsx
  components/Common/TopBar/TopBar.styles.ts
  components/Layout/Game/Character.tsx
  components/Layout/Game/CountdownButton.tsx
  components/Layout/Game/Timer.styles.ts
  components/Layout/Game/Timer.tsx
  hooks/inGame/useGameState.ts
  hooks/inGame/useGameSubmit.ts
  hooks/inGame/useGameTimer.tsx
  stories/Common/ValidationMessage.stories.tsx
Labels: 🐛 bug, ♻️ refactor

#61 deploy : 배포 에러 해결(5)
  stories/Layout/Signup/NickNameInput.stories.ts
Labels: 🐛 bug

#64 style: 그룹 리스트 CSS 변경 및 카드 컴포넌트, 애니메이션 추가
  app/(nav)/groupList/groupList.styles.ts
  app/(nav)/groupList/page.tsx
  components/Common/NavBar/NavBar.tsx
  components/Common/RoomButton/RoomButton.styles.ts
  components/Layout/Home/MainBanner/Level.styles.ts
  components/Layout/Home/MainBanner/MainBanner.styles.ts
Labels: 🎨 design

#67 Feature/#65 온보딩 UI 제작, 인게임 게임제출 비활성화 기능, 대기방 CSS 수정
  app/(auth)/login/page.tsx
  app/(nav)/home/page.tsx
  app/commonPage.styles.ts
  app/game/[roomId]/[round]/game.styles.ts
  app/game/[roomId]/[round]/page.tsx
  app/game/[roomId]/waitingRoom/waitingRoom.styles.ts
  app/homePage.styles.ts
  app/onBoarding.styles.ts
  app/page.tsx
  components/Layout/Game/Character.styles.ts
  components/Layout/Game/Character.tsx
  components/Layout/Game/GoogleMap.tsx
  hooks/inGame/useGameState.ts
  package-lock.json
  package.json
Labels: ✨ feature, 🎨 design
