Repository prgrms-web-devcourse-final-project/WEB1_1_Urdego_FE, pull requests merged in 2024-12, with the labels that each got.

#70 Feature/#69 socket file
  app/(nav)/myPage/page.tsx
  app/layout.tsx
  components/Common/NavBar/NavIcon.tsx
  components/Common/TopBar/TopBar.styles.ts
  components/Layout/Home/MainBanner/Level.styles.ts
  components/Layout/Home/MainBanner/Level.tsx
  package-lock.json
  package.json
  socket/README.md
  socket/constants/events.ts
  socket/hooks/useGameSocket.ts
  socket/hooks/useWaitingRoomSocket.ts
  socket/instance/socket.ts
  socket/services/game.service.ts
  socket/services/waitingRoom.service.ts
  socket/types/socket.types.ts
Labels: ✨ feature

#76 Feature/#72 로그인, 회원가입 고쳐야 할 것들 고쳤습니다.
  app/(auth)/login/page.tsx
  app/(auth)/signup/page.tsx
  components/Common/ValidationMessage/ValidationMessage.styles.ts
  components/Common/ValidationMessage/ValidationMessage.tsx
  components/Layout/MakeRoom/FriendsInviteForm.styles.ts
  components/Layout/Signup/NickNameInput.tsx
  styles/color/palette.ts
Labels: ✨ feature, 🐛 bug, 📝 docs

#75 Feature/#68: 장소 등록하기에서 구글맵 활용한 위치 추가하기 구현
  app/(nav)/locationRegister/[index]/locationRegister.styles.ts
  app/(nav)/locationRegister/[index]/page.tsx
  app/(nav)/placeRegister/page.tsx
  app/commonPage.styles.ts
  app/layout.tsx
  app/metadata.ts
  components/Layout/LocationRegister/GoogleMap.tsx
  components/Layout/PlaceRegister/PlaceRegister.tsx
  components/Layout/PlaceRegister/PlaceSearchButton.styles.ts
  components/Layout/PlaceRegister/PlaceSearchButton.tsx
  hooks/placeRegister/useContorlButtons.ts
  hooks/placeRegister/useUploadFiles.ts
  package-lock.json
  package.json
  stores/placeRegisterStore.ts
Labels: ✨ feature, 🎨 design

#77 style: 온보딩 UI 제작
  app/(auth)/login/Login.styles.ts
  app/(auth)/signup/Signup.styles.ts
  app/onBoarding.styles.ts
  app/page.tsx
  styles/Icon/OnBoarding2.svg
  styles/Icon/OnBoarding3.svg
  styles/Icon/OnBoarding4.svg
Labels: 🎨 design

#78 Feature: loading spinner 및 정답 제출 API 작성
  app/game/[roomId]/[round]/game.styles.ts
  app/game/[roomId]/[round]/page.tsx
  app/game/[roomId]/waitingRoom/page.tsx
  app/game/layout.tsx
  app/layout.tsx
  components/Common/LoadingSpinner/LoadingSpinner.style.tsx
  components/Common/LoadingSpinner/LoadingSpinner.tsx
  components/Layout/Game/Swiper.styles.ts
  hooks/Loading/RouteChangeHandler.tsx
  hooks/inGame/useGameSubmit.ts
  stores/loadingStore.ts
  styles/Icon/LoadingSpinner.gif
Labels: ✨ feature, 🎨 design

#81 Feature/#73: 장소 등록하기에서 메타 데이터 활용하여 위치 자동 할당 구현 및 API 엔드 포인트 도메인 적용
  app/(nav)/placeRegister/layout.tsx
  app/api/content/route.ts
  app/layout.tsx
  components/Common/LoadingSpinner/LoadingSpinner.style.tsx
  components/Common/LoadingSpinner/LoadingSpinner.tsx
  components/Layout/LocationRegister/GoogleMap.tsx
  hooks/placeRegister/useConvertLocationToAddress.ts
  hooks/placeRegister/useRegisterFiles.ts
  package-lock.json
  package.json
Labels: ✨ feature

#83 Fix/#82: 배포에서 스토리북 에러 해결
  stories/Common/ValidationMessage.stories.tsx
Labels: 🐛 bug

#84 Fix: PlaceRegister Page useSearchParams() 문제 해결 위해 layout에 Suspense 추가
  app/(nav)/placeRegister/layout.tsx
Labels: 🐛 bug

#88 Style: 초대 Toast 제작 및 route 설정
  app/(nav)/home/Home.styles.ts
  app/(nav)/home/page.tsx
  components/Common/TopBar/TopBar.tsx
  components/Layout/Home/InviteToast/InviteToast.styles.ts
  components/Layout/Home/InviteToast/InviteToast.tsx
Labels: 🎨 design

#92 Style/#91: 온보딩 겹치는 문제 해결
  app/onBoarding.styles.ts
Labels: 🐛 bug, 🎨 design

#94 Feature/#54 대기방 소켓 연결, 대기방 채널 연결
  app/(auth)/login/page.tsx
  app/(nav)/home/page.tsx
  app/api/login/route.ts
  app/api/makeRoom/route.ts
  app/api/notification-service/connect/[userId]/route.ts
  app/makeRoom/page.tsx
  components/Layout/MakeRoom/FriendsInviteForm.tsx
  config/apiEndPointConfig.ts
  hooks/useSSEConnection.ts
  lib/types/notification.ts
  package-lock.json
  package.json
  stores/useGameStores.ts
  stores/useSSEStore.ts
Labels: ✨ feature

#98 feat: SSE 적용
  app/(auth)/login/page.tsx
  app/(nav)/home/page.tsx
  app/api/notification-service/connect/[userId]/route.ts
  app/makeRoom/page.tsx
  components/Layout/MakeRoom/FriendsInviteForm.tsx
  package-lock.json
  stores/useSSEStore.ts
  stores/useUserStore.ts
Labels: ✨ feature

#100 feat: http error
  app/api/invite/route.ts
  components/Layout/MakeRoom/FriendsInviteForm.tsx
Labels: 🐛 bug

#104 fix: round/page.tsx 충돌해결
  app/game/[roomId]/[round]/page.tsx
Labels: 🐛 bug

#105 fix: SSE 최적화
  app/(nav)/home/page.tsx
  app/api/notification-service/connect/[userId]/route.ts
Labels: 🐛 bug, ♻️ refactor

#107 feature/#106 소켓연결을 next.config.js 를 사용 해서 우회하여 사용하는 방법을 사용
  app/makeRoom/page.tsx
  next.config.mjs
Labels: 🐛 bug

#109 fix: next.config.mjs 경로 fix
  app/makeRoom/page.tsx
  config/apiEndPointConfig.ts
  next.config.mjs
Labels: 🐛 bug

#112 fix: 초기 undefined 이슈 해결
  app/game/[roomId]/waitingRoom/page.tsx
Labels: 🐛 bug

#115 Feat/#113 게임 시작전 까지 소켓 통신
  app/(nav)/home/page.tsx
  app/game/[roomId]/waitingRoom/page.tsx
  app/makeRoom/page.tsx
  lib/websocket/waittingRoomWebsocket.ts
  stores/types/websocket.ts
  stores/useWebSocketStore.ts
Labels: ✨ feature

#117 Feat/#116-game socket connect
  app/game/[roomId]/waitingRoom/page.tsx
  config/apiEndPointConfig.ts
  lib/websocket/gameWebsocket.ts
  lib/websocket/waittingRoomWebsocket.ts
  stores/useIngameStore.ts
  stores/useWebSocketStore.ts
Labels: ✨ feature

#122 feat/#80-toast UI setting, backgroundImage 경고 문제 해결
  app/(nav)/home/page.tsx
  components/Common/RoomButton/RoomButton.styles.ts
  components/Common/RoomButton/RoomButton.tsx
Labels: ✨ feature, 🎨 design

#127 Feature: test 환경 셋팅
  app/game/[roomId]/[round]/page.tsx
  app/game/[roomId]/[round]/roundRank/page.tsx
  components/Layout/Game/GoogleMap.tsx
  lib/websocket/gameWebsocket.ts
  next.config.mjs
Labels: ✨ feature, 🐛 bug

#128 fix: next.config.js 삭제
  next.config.js
Labels: 🐛 bug

#132 test: bundle-analyzer를 활용한 번들 용량 체크
  app/api/game/route.ts
  app/game/[roomId]/[round]/page.tsx
  components/Layout/Game/Character.styles.ts
  components/Layout/Home/MainBanner/Level.styles.ts
  next.config.mjs
  package-lock.json
  package.json
Labels: ♻️ refactor
